"""add_tables_and_order_table_id

Revision ID: 865e2323fc47
Revises: 2a9135927e28
Create Date: 2026-03-02 04:45:35.304995
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865e2323fc47'
down_revision: Union[str, None] = '2a9135927e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('qr_token', sa.String(length=50), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'table_number', name='uq_restaurant_table_number')
    )
    op.create_index(op.f('ix_tables_qr_token'), 'tables', ['qr_token'], unique=True)
    op.create_index('ix_tables_restaurant_active', 'tables', ['restaurant_id', 'is_active'], unique=False)
    op.add_column('orders', sa.Column('table_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'tables', ['table_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'table_id')
    op.drop_index('ix_tables_restaurant_active', table_name='tables')
    op.drop_index(op.f('ix_tables_qr_token'), table_name='tables')
    op.drop_table('tables')
    # ### end Alembic commands ###
