"""add google maps url

Revision ID: a895af839b8a
Revises: 865e2323fc47
Create Date: 2026-03-02 06:57:17.175011
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a895af839b8a'
down_revision: Union[str, None] = '865e2323fc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('google_maps_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'google_maps_url')
    # ### end Alembic commands ###
